In [2]:
import pandas as pd

In [7]:
variables = ["kohde","jasen","pvknro","sp","IKAL1","ASALUE","V1","V21","V32","V40","H1a_A","H1h_A"]

pd.read_csv("habits.data",delimiter=";")

,kohde,jasen,pvknro,sp,ASALUE,IKAL1,V1,V5,V7,V21,...,V40,V68,V69,V70,V75,H1a_A,H1b_A,H1g_A,H1h_A,H1i_A
0,50007,2,2,2,3.0,6,580,0,20,0,...,0,30,0,0,0,1.0,1.0,2.0,1.0,2.0
1,50009,1,1,2,1.0,7,0,40,0,0,...,0,240,0,60,0,1.0,1.0,2.0,1.0,1.0
2,50015,1,1,1,3.0,8,0,10,0,0,...,0,310,10,240,0,2.0,1.0,2.0,1.0,2.0
3,50032,2,1,1,2.0,8,0,0,10,0,...,0,0,0,170,0,2.0,2.0,2.0,2.0,2.0
4,50033,1,1,2,1.0,8,00:00,02:10,00:20,00:00,...,00:00,00:30,00:00,01:50,00:00,2.0,2.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,51943,1,2,2,1.0,4,440,30,10,0,...,0,10,0,80,0,1.0,1.0,1.0,2.0,1.0
389,51947,2,1,2,1.0,7,490,0,10,0,...,0,0,0,70,10,1.0,1.0,2.0,1.0,2.0
390,51956,1,1,2,2.0,6,0,30,0,0,...,0,30,0,170,50,1.0,1.0,2.0,1.0,2.0
391,51957,2,2,2,1.0,7,0,10,10,0,...,0,60,0,30,40,2.0,2.0,1.0,1.0,2.0
392,51964,2,1,1,1.0,7,0,30,0,0,...,0,0,0,400,0,1.0,2.0,2.0,?,1.0